### ISSUE TITLE
Repository Deprecated

### ISSUE THREAD

**Issue by blacklabelops** [atldocker/jira#119]
I will stop supporting and implementing Docker images starting in early 2019.

Repositories will be transferred to blacklabelops-legacy and archived for read only purpose.

The following repositories and images are affected:

January 2019 
* blacklabelops/crowd
* blacklabelops/nginx
* blacklabelops/bitbucket
* blacklabelops/java
* blacklabelops/letsencrypt
* blacklabelops/postgres

March 2019
* blacklabelops/baseimages
* blacklabelops/confluence
* blacklabelops/jira
* blacklabelops/volumerize
* blacklabelops/logrotate

**Comment by frederikkunze** [comment]
Why did you come to this decision? Are you not using Atlassian products anymore or did you switch to another image yourself?

**Comment by blacklabelops** [comment]
Due to my career path. I am more involved in development than ops. I am not even involved with anything Docker related.

The images are state of the art but they cost maintenance time.

This had been fun but it's time to make place for something new.

**Comment by frederikkunze** [comment]
Then I wish you the best for your future path. 👍 
I have to work a bit on understanding docker better so I may can jump in and maintain my own images soon. 
You did a great job with this it inspires a lot of people I guess. 🥇

**Comment by jhult** [comment]
More discussion on a transition plan can be found here: https://github.com/blacklabelops/confluence/issues/61

**Comment by jhult** [comment]
Transfer complete
