### ISSUE TITLE
Switch to using AdoptOpenJDK

### ISSUE THREAD

**Issue by Firefishy** [atldocker/jira#122]
Atlassian are now switching to using AdoptOpenJDK since 7.13+
https://confluence.atlassian.com/jirasoftware/jira-software-7-13-x-release-notes-957981568.html#JiraSoftware7.13.xreleasenotes-AdoptOpenJDK8comestoJira

Likely best to switch to docker image `adoptopenjdk/openjdk8:alpine` for the `FROM`.

**Comment by Firefishy** [comment]
https://hub.docker.com/r/adoptopenjdk/openjdk8

**Comment by blacklabelops** [comment]
This image uses the jdk coming along with jira. It will be okay as long the JDK with run inside alpine.

**Comment by jhult** [comment]
[As of 8.0](https://confluence.atlassian.com/adminjiraserver/supported-platforms-938846830.html), Atlassian is still bundling Oracle JRE 8.

> Unlike Oracle JRE, AdoptOpenJDK is not bundled with the Jira installers, and you need to install it on your own.

The reason for possibly switching is mentioned [here](https://confluence.atlassian.com/jirasoftware/jira-software-7-13-x-release-notes-957981568.html#JiraSoftware7.13.xreleasenotes-AdoptOpenJDK8comestoJira):

> Oracle will stop providing public updates for Oracle JDK 8 in January. This means that only Oracle customers with a paid subscription or support contract will be eligible for updates.  
> 
> In order to provide you with another option, we now support running Jira 7.13 with AdoptOpenJDK 8. AdoptOpenJDK is free to use, and provides regular maintenance and security updates. Paid support for AdoptOpenJDK is also available from organisations such as IBM.

Here is some additional reading:

- [Java 11 and OpenJDK support for Atlassian Server & Data Center products](https://community.atlassian.com/t5/Jira-discussions/Java-11-and-OpenJDK-support-for-Atlassian-Server-amp-Data-Center/td-p/872998)
- [How to run Jira Server on AdoptOpenJDK](https://confluence.atlassian.com/jirakb/how-to-run-jira-server-on-adoptopenjdk-966036766.html)
- [Java Is Still Free](https://medium.com/@javachampions/java-is-still-free-c02aef8c9e04)

**Comment by unquietwiki** [comment]
* https://github.com/AdoptOpenJDK/openjdk-docker
* https://hub.docker.com/r/atlassian/confluence-server/tags

The official Confluence image switched some time ago; been fine in my environment. I wish I understood why they don't offer an official Jira image: it'd make the work here redundant, but they are the vendor...

**Comment by jhult** [comment]
A few notes:

1. I made the choice to use OpenJ9. See [here](https://www.eclipse.org/openj9/) for more information. If so desired, you can change this back to HotSpot by updating top line of the [Dockerfile](/atldocker/jira/blob/master/Dockerfile) and build yourself.

2. Atlassian is going to switch the bundled installer from Oracle JDK to use AdoptOpenJDK 8 in 8.2+ and AdoptOpenJDK 11 in 8.4+. See [here](https://community.atlassian.com/t5/Agile-articles/Java-11-OpenJDK-support-update-for-Server-and-Data-Center/ba-p/967836) for more information.

3. Jira does not currently work with 11.2.x. See [here](https://confluence.atlassian.com/jirakb/how-to-start-jira-8-0-with-openjdk-11-and-sql-server-962974092.html) for more information. Supposedly it works with 11.1.x but I have not yet confirmed this.
