### ISSUE TITLE
Jira Software 8.0

### ISSUE THREAD

**Issue by 1aGh** [atldocker/jira#125]
Hi,

when will be possible to upgrade to Jira software 8.0?

Thank you

**Comment by jhult** [comment]
Now that we are in our new repository, hopefully, we can get this rolled out in the next week or two.

**Comment by rwarren** [comment]
Is anybody actively looking at bumping to 8.0?

**Comment by EugenMayer** [comment]
Should you be in dire need, i got 8.0.0 (8.0.2) for a while now https://github.com/EugenMayer/docker-image-atlassian-jira - maybe this can help you out. It is a fork of this repo a while ago, so might work as a drop in replacement for you ( for now ) - or whatever you might need ( temporary or not ).

I am usually packaging the images on the date of release of the product version.

**Comment by maxdanilov** [comment]
@jhult Any ETA on when 8.0 is available? Thank you 🙇

**Comment by mdeboer** [comment]
PR #127 is up, anyone care to test?

**Comment by mdeboer** [comment]
@EugenMayer I really needed 8 so I upgraded using your image, works fantastic!

**Comment by jhult** [comment]
I am working on pulling in some updates from @EugenMayer and other updates. Hopefully will have some news in the next few days. Sorry for the delay.

**Comment by jhult** [comment]
This was closed as part of #128.

FYI, for the moment, you will need to manually build until we sort out the Docker Hub issue (see atldocker/confluence#61 for more info.)
