### ISSUE TITLE
Fonts problem

### ISSUE THREAD

**Issue by 1aGh** [atldocker/jira#126]
Hi,

is it possible to add line into dockerfile for install Google fonts? I have problem with exporting PDF via Xporter plugin and I think that it's because there are no fonts installed in docker.

I tried to installed it manualy in docker but I don't have a rights to use "apk add" and I don't know how to obtain this. Also this will be only temporary solution, because after every contaniner restart the fonts will be gone.

Any idea how to achieve this?

Thank you
Michal

**Comment by Firefishy** [comment]
What fonts are you interested in? Ideally packages.

**Comment by 1aGh** [comment]
Well according this documentation it is possible to install some basic Microsoft fonts. I think It can be good start because Xporter is using Microsoft Word for templates.

msttcorefonts-installer

https://wiki.alpinelinux.org/wiki/Fonts

I'm using IBM Plex font family but I didn't find any package for Alpine Linux. I think this have to be done manually. 
Or, and this is only an idea, we can mount Volume for fonts to ~/.fonts in Alpine, and everyone can add his fonts by his own.

https://medium.com/@vladimirsalin/bring-your-favourite-fonts-to-reports-running-in-docker-9fc2d24e2b03

What do you think?

**Comment by Firefishy** [comment]
This was resolved in Confluence container by: https://github.com/atldocker/confluence/issues/18 and https://github.com/atldocker/confluence/commit/2e361e83277fff29b76c73780e02810853c3b885

**Comment by 1aGh** [comment]
Oh that's perfect, can we add this to Jira container?
